version: '3.8'

services:
  nhc-property-tax-server:
    build: .
    container_name: nhc-property-tax-server
    ports:
      - "8000:8000"
    environment:
      # Data storage
      - DATA_DIR=/app/data
      
      # Request configuration
      - RETRY_ATTEMPTS=${RETRY_ATTEMPTS:-3}
      - RETRY_DELAY=${RETRY_DELAY:-2.0}
      - RETRY_BACKOFF=${RETRY_BACKOFF:-2.0}
      
      # Rate limiting
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_DELAY=${RATE_LIMIT_DELAY:-1.0}
      
      # Caching
      - CACHE_ENABLED=${CACHE_ENABLED:-true}
      - CACHE_DURATION_HOURS=${CACHE_DURATION_HOURS:-24}
      - CACHE_MAX_SIZE=${CACHE_MAX_SIZE:-5000}
      
      # Result limits
      - MAX_RESULTS=${MAX_RESULTS:-500}
      
      # Security (optional)
      - MCP_API_KEY=${MCP_API_KEY:-}      
      # Server configuration
      - PORT=${PORT:-8000}
    
    volumes:
      # Persist data directory
      - ./data:/app/data
      
      # Mount .env file if exists
      - ./.env:/app/.env:ro
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    networks:
      - mcp-network

  docs-server:
    build: .
    container_name: nhc-property-tax-docs
    command: python docs_server.py
    ports:
      - "8001:8001"
    environment:
      - DOCS_PORT=8001
    volumes:
      - ./swagger_docs.py:/app/swagger_docs.py:ro
      - ./docs_server.py:/app/docs_server.py:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network
    depends_on:
      - nhc-property-tax-server

networks:
  mcp-network:
    driver: bridge